### ISSUE TITLE
give repo URL explicitly

### ISSUE THREAD

**Issue by rdiaz02** [remlapmot/cibookex-r#4]
In file `cibookex-r/index.Rmd `, where you say "please copy/fork the repository", maybe it would be good to give the repo URL explicitly, since where the repo is located is not totally obvious if one is redirected to https://remlapmot.github.io/cibookex-r/ from the book's web page.

P.S. Thanks for the repo!

**Comment by remlapmot** [comment]
Thanks for the comment.

I have added some more details to that section.
